# Generated by Django 3.2.6 on 2021-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('beds_count', models.IntegerField(default=1)),
                ('baths_count', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
