# Generated by Django 3.2.6 on 2021-09-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='listing-images')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='main.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='main.ListingImage'),
        ),
    ]
