# Generated by Django 3.2.6 on 2021-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='application_fee',
            field=models.IntegerField(default=1),
        ),
    ]
